### ISSUE TITLE
Does not work when using m.route() instead of m.mount()

### ISSUE THREAD

**Issue by JoeLanglois** [capaj/jspm-mithril#1]
Hey there, thanks for the starter-kit.
Unfortunately, when using m.route(elem, default, routes), the hot-reloading just stops working.

The files are reloaded but it has no effect on the page.

Any idea how to fix this?

**Comment by capaj** [comment]
@JoeDRL for react-router, we have to use this special render-forcer: https://github.com/capaj/jspm-react/blob/master/public/app.js#L15

I suspect something similar can be made for mithrill.

**Comment by capaj** [comment]
@JoeDRL fixed in 440f55bd

**Comment by JoeLanglois** [comment]
Great! Thanks
